=== Munyeshya/XML/library.dtd
<!ELEMENT library (books)>


<!ELEMENT books (book+)>
<!ELEMENT book (id, title, author, publicationYear, isbn)>

<!ELEMENT id (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT publicationYear (#PCDATA)>
<!ELEMENT isbn (#PCDATA)>

=== Munyeshya/XML/library.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE library SYSTEM "library.dtd">
<library>
    <books>
        <book>
            <id>1</id>
            <title>The Great Gatsby</title>
            <author>F.Scott Fitzgerald</author>
            <publicationYear>1925</publicationYear>
            <isbn>978-0-7432-7432-7356-5</isbn>
        </book>
        <book>
            <id>2</id>
            <title>To Kill a Mockingbird</title>
            <author>Harper Lee</author>
            <publicationYear>1960</publicationYear>
            <isbn>978-0-06-112008-4</isbn>
        </book>
        <book>
            <id>3</id>
            <title>1984</title>
            <author>George Orwell</author>
            <publicationYear>1949</publicationYear>
            <isbn>978-0-452-28423-4</isbn>
        </book>
        <book>
            <id>4</id>
            <title>Pride and Prejudice</title>
            <author>Jane Austen</author>
            <publicationYear>1813</publicationYear>
            <isbn>978-0-14-143951-8</isbn>
        </book>
    </books>
</library>
